@startuml

actor Alicрe
actor Alice
actor Bob

' ***

Alicрe -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response

@enduml