@startuml

interface Foo{
  +val() : Number
  +get_val(das,) : Number
}

class Bar{

}

interface FF {
  do_it()
  +do_it()
}

enum das {
das 
asd

}

Bar <|-down-|> Foo : dasda
АААА --> DDD

@enduml
