@startuml

actor teacher  
entity student_database
boundary "main menu screen" as main_menu_screen
boundary "add student screen" as add_student_screen 
control "display add student screen" as display_add_student_screen
control "display main menu" as display_main_menu
control "display notification student added successful" as display_notification_student_added_successful
control "add student" as add_student

teacher -- main_menu_screen 
teacher -- add_student_screen

main_menu_screen --> display_add_student_screen : add button pressed

display_add_student_screen --> add_student_screen
display_main_menu --> main_menu_screen

add_student_screen -- add_student : "next button pressed"
add_student --> student_database : "successful"
add_student --> display_main_menu : "successful"
add_student --> display_notification_student_added_successful : "successful"

note right of teacher:ds


note right of main_menu_screen : "This is boundary object"
note right of student_database : This is entity object 
note right of add_student : This is control object 
note as scenario
Главная последовательность:
    1) учитель выбирает в главном меню пункт “добавить ученика“;
    2) система показывает учителю окно добавления ученика, 
         содержащее поля для ввода логина и пароля, 
         а также кнопки “далее” и “назад”;
    3) учитель вводит желаемый логин и пароль 
         ученика, нажимает кнопку “далее”;
    4) система добавляет ученика;
    5) учителю открывается главное меню и в течении 5 секунд
        выводится уведомление о том, что ученик был добавлен успешно.
end note

@enduml
